#!/usr/bin/env bash
set -e

export DOCKER_BUILDKIT=1

rm -rf $(dirname $0)/Dockerfile.run.build
cp $(dirname $0)/Dockerfile $(dirname $0)/Dockerfile.run.build


sed -i '/from debian:trixie/i\# HEAD LINE' Dockerfile.run.build
sed -i '/from debian:trixie/a\# RUN LINE' Dockerfile.run.build

sed -i 's#from debian:trixie#from 192.168.13.73:5000/debian:trixie#g' Dockerfile.run.build

sed -i '/# HEAD LINE/i\# syntax=192.168.13.73:5000/docker/dockerfile:1.3' Dockerfile.run.build

sed -i '/# RUN LINE/i\run apt update' Dockerfile.run.build
sed -i '/# RUN LINE/i\run apt install -y apt-transport-https ca-certificates' Dockerfile.run.build
sed -i '/# RUN LINE/i\run sed -i "s,http://deb.debian.org/,https://mirrors.tuna.tsinghua.edu.cn/,g" /etc/apt/sources.list.d/debian.sources' Dockerfile.run.build
sed -i '/# RUN LINE/i\run apt update' Dockerfile.run.build

if [ $(arch) == "arm64" ] || [ $(arch) == "aarch64" ]; then
    sed -i 's/grep ttyd.x86_64/grep ttyd.aarch64/g' Dockerfile.run.build
    sed -i 's/grep amd64/grep arm64/g' Dockerfile.run.build
    sed -i 's/grep linux_x86_64/grep linux_aarch64/g' Dockerfile.run.build
fi

time ./build.sh 192.168.13.73:5000/sleechengn/debian-$(arch):trixie
time docker push 192.168.13.73:5000/sleechengn/debian-$(arch):trixie
./build.sh sleechengn/debian-$(arch):trixie
rm -rf $(dirname $0)/Dockerfile.run.build
